path:
  ckpt_path: "./output/ckpt/MLVAEv2CMUsingle128k"
  log_path: "./output/log/MLVAEv2CMUsingle128k"
  result_path: "./output/result/MLVAEv2CMUsingle128k/"
  array_path: "./output/arrays/MLVAEv2CMUsingle128k/"
  plot_path: "./output/plots/MLVAEv2CMUsingle128k"
optimizer:
  mask_padding: True # set model's padded outputs to padded values
  guided_attn: True # apply diagonal guided attention loss
  guided_sigma: 0.4
  guided_lambda: 1.0
  fp16_run: False
  batch_size: 64
  betas: [0.9, 0.999]
  eps: 0.00000001
  weight_decay: 0.000001
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  init_lr: 0.001
step:
  total_step: 900000
  log_step: 100
  synth_step: 500
  val_step: 2500
  save_step: 5000

cyclic_anneling:
  start: 1.0
  stop: 1.0
  n_cycle: 4
  ratio: 0.5

linbuildkl:
  type: "expo"
  start: -2
  stop: 0
  n_up: 5000
  n_stop: 15000

linbuildadv:
  type: "expo"
  start: 0
  stop: 0
  n_up: 0
  n_stop: 2500

linbuildce:
  type: "expo"
  start: 0
  stop: 0
  n_up: 0
  n_stop: 2000

coeffs:
  acc_kl: 0.0001
  spk_kl: 0.0001
  acc_adv: 0.01
  spk_adv: 0.0
  acc_ce: 0.1
  spk_ce: 0.0
  reco: 1